### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by tokersey** [RevSquare/django-brightcove#1]
Hello,

The documentation for this is slightly incorrect. Here are a couple of issues I found.

In the installed apps it stays add `django-brightcove` to your app list. It should actually be `django_brightcove` since the app includes and underscore instead of a dash.

For the template tag, it show `video_id` returning the video to be used in the tag template. However, 'video_id' does not exist in the code. Instead, I found that `object.brightcove_id` should be used to get video id like this:

```
{% brightcove_player object.brightcove_id width=480 height=270 %}
```

Thanks

**Comment by omji** [comment]
Thanks a million for your help and feedback Todd. Sorry for the inconvenience about the errors in the documentation.
