### ISSUE TITLE
"default" player is somewhat random.

### ISSUE THREAD

**Issue by mrmachine** [RevSquare/django-brightcove#4]
The README says the "first" item in `BRIGHTCOVE_PLAYERS` setting (a dict) is the default. Dict keys are unordered. Given the same keys, the order is consistent, but it's not specified. So you could have a player named "default" that is not the default depending on what other players you have defined.

Instead, the template tag should get the player named "default" if no player name is given.

**Comment by omji** [comment]
You are absolutely right! I have fixed this and updated the documentation according to your suggestion. Many thanks for your help!

**Comment by omji** [comment]
It is bundled in a new release ( 0.0.4) on pypi
