### ISSUE TITLE
KeyErrors will themselves raise exceptions due to misplaced %

### ISSUE THREAD

**Issue by poisontofu** [RevSquare/django-brightcove#8]
In the `templatetags/brightcove.py` file, on lines 23 and 29, the `%` should immediately follow the string, e.g:

```
    raise KeyError('%s player type […]') % player
```

should be: 

```
    raise KeyError('%s player type […]' % player)
```

**Comment by omji** [comment]
Wow indeed! Thanks a lot for pointing that out. Should be fixed now.
